### ISSUE TITLE
Procedural probe core EC capacity grows exponentially when reverting to launch

### ISSUE THREAD

**Issue by Nazfib** [KSP-RO/RP-1#2003] opened 2023-06-11 23:10 UTC
Every time an ROTanks procedural probe core loads into the flight scene, the electric charge capacity of the core multiplies by some constant factor.

Reproduction steps:
- Load a sandbox save with KCT disabled
- In the VAB, create a new vessel consisting of only  a "Procedural Probe Core".
- In the avionics config screen, select "Science core", "Modern Avionics", EC amount: 500, "Apply (preserve dimensions)"
- Click launch. The probe core now has 500/2131 electric charge (amount/capacity)
- Press escape; revert to launch. The probe core now has 500/9085 EC
- Press escape; revert to launch. The probe core now has 500/38724 EC

Logs are attached.
[KSP.log](https://github.com/KSP-RO/RP-1/files/11715965/KSP.log)
[Player.log](https://github.com/KSP-RO/RP-1/files/11715966/Player.log)

**Comment by NathanKell** [comment] 2023-06-11 23:21
Gonna assume this is more fallout from the shipmodified stuff?

**Comment by siimav** [comment] 2023-06-14 21:57
Cannot replicate in neither my dev install nor the full one.

**Comment by siimav** [comment] 2023-06-14 22:11
Looked at my log and yours side by side and couldn't find any relevant differences.

**Comment by Nazfib** [comment] 2023-06-17 12:17
Update: had some time today to track it down. You're right, it does not happen in a clean RP-1 Express install.

The offending mod is Dynamic Battery Storage. When I install that, and nothing else besides the express install, the issue appears. Even though it's supposed to fully disable itself when it detects Kerbalism, apparently it still screws something up somewhere.

**Comment by siimav** [comment] 2023-06-17 12:56
Could very well be that the lifecycle is messed up in that mod. 
https://github.com/post-kerbin-mining-corporation/DynamicBatteryStorage/blob/master/Source/DynamicBatteryStorage/DynamicBatteryStorage.cs#L55
https://github.com/post-kerbin-mining-corporation/DynamicBatteryStorage/blob/master/Source/DynamicBatteryStorage/Settings.cs#L58
Usually Awake gets called before OnLoad. Not 100% if that's the case for VesselModules as well.

Or could just be that the disabling was done partially.
https://github.com/post-kerbin-mining-corporation/DynamicBatteryStorage/blob/master/Source/DynamicBatteryStorage/DynamicBatteryStorage.cs#L100-L127

**Comment by bofhgr** [comment] 2023-06-20 13:29
I have experienced this issue with using a procedural probe core from Nertea's Near Future Exploration mod. I have been able to replicate by launching a rocket, have it break up mid flight and hitting escape then revert to launch. Each time the battery amount in the probe increases, making the rocket heavier and it won't go away even after recovering the rocket - in fact you will be recovering a much heavier rocket than the one you put on the pad and by scrapping it you would net more money that it costed to build it in the first place.

If it helps, I have a save file and craft file to help reproduce it, let me know if I should share these.

**Comment by siimav** [comment] 2023-06-20 13:32
No need. It's clear that the issue is caused by DynamicBatteryStorage. The fix right now is to just remove the mod.

**Comment by bofhgr** [comment] 2023-06-20 14:03
Just to note here that removing this mod also forces removal of the mods as seen in the screenshot:

![dynamic bat storage remove dependencies](https://github.com/KSP-RO/RP-1/assets/28956359/55687a80-cd6e-45e8-a6e2-5bc93cd5d670)

Kindly note that in this page from the wiki: https://github.com/KSP-RO/RP-1/wiki/Extra-Mods-to-Consider
The Kerbal Atomics and Cryo Engines (from the Rocket Parts section) as well as the Near Future Electrical (from the Misc Parts) require this mod in order to work - so probably anyone who has added these mods have this potential issue in their installs.

Until this issue is addressed, perhaps not recommending these mods in the wiki might be best.

**Comment by Capkirk123** [comment] 2023-06-20 19:24
We could probably just recommend manually installing those mods and conflict DBS in CKAN. I also believe there are efforts underway to take a more aggressive approach when disabling DBS in the presence of Kerbalism.

**Comment by pap1723** [comment] 2023-06-24 03:46
Fixed in Realism Overhaul by forcefully disabling DBS.

**Closed by pap1723** 2023-06-24 03:46 UTC
