### ISSUE TITLE
Avionics causes mass to be NaN and leads to CTD

### ISSUE THREAD

**Issue by alexban011** [KSP-RO/RP-1#2321] opened 2024-01-08 22:33 UTC
Replacing the avionics at the top resolves the issue. If you need me to do more testing I'll be glad to do it.

![image](https://github.com/KSP-RO/RP-1/assets/21990802/c9db2226-1a44-4695-9768-8601b5a68493)
[craftFileAndLog.zip](https://github.com/KSP-RO/RP-1/files/13866821/craftFileAndLog.zip)

**Comment by siimav** [comment] 2024-01-09 11:09
Duplicate of https://github.com/KSP-RO/RP-1/issues/2313

**Closed by siimav** 2024-01-09 11:09 UTC
