### ISSUE TITLE
ProceduralAvionics kOS diskspace

### ISSUE THREAD

**Issue by timflapper** [KSP-RO/RP-1#1251] opened 2020-04-20 11:35 UTC
Hi!

I'm noticing extremely low amounts of disk space on the kOSprocessor of the ProceduralAvionics part. Something that seems to have been integrated 12 days ago in https://github.com/KSP-RO/RP-0/pull/1234. I feel that this is heavily penalising players that program their rockets vs players that fly manually or use MechJeb. In reality there would have been at least a mechanical gyro with very basic electronics on any rocket with steering capabilities. I simulate this using kOS which in my opinion is much more realistic than manual flying no matter how much code it requires to do so.

I know there are ways around disk space by simply loading from "0:/" but I think that kind of defeats the purpose.

Perhaps this can start a discussion on values that restrict players in using overly complicated scripts while still allowing the flexibility of writing simple code, especially when starting a new career.

**Comment by RCrockford** [comment] 2020-04-20 11:40
The disk space is set up such that early probes need to run from archive (0:/) as that is representative of their capabilities. There is no penalty for running off 0:/ other than needing a connection to base, which is what the configs are intended to promote.
Putting many kilobytes of storage and allowing early probes to be completely autonomous is not really a realistic approach.

**Comment by siimav** [comment] 2020-07-05 12:50
@RCrockford is it fixed now?

**Comment by szundi** [comment] 2020-09-19 10:22
Hello, should this be the intended behavior, this could be closed with result won'tfix then.

**Closed** 2023-07-02 20:58 UTC
Labels: Ready To Close?
